/* ─────────────────────────────────────────────────────────────────────────────
   LEVEL 2 — Normalized entity model.

   Deliberately generic: no travel-only or shopping-only fields at the top
   level. `image` is OPTIONAL and every archetype must remain valid without
   it — real corpus traces frequently carry no usable image at all (see
   PHOENIX_SCENARIO_ARCHETYPES.md). Renderers decide the visual fallback;
   this layer never invents one.

   ENTITY vs ATTRIBUTE vs SUPPORTING INFORMATION is a semantic distinction,
   not a styling one — see classification/entityRole.ts. Only `entity`-role
   objects may ever appear in a candidate-ranking or comparison set; a
   "Booking Tips" or "Group Size & Pricing" block is real content the agent
   emitted, but it is not a selectable peer and must never be ranked against
   one.
   ───────────────────────────────────────────────────────────────────────────── */

export type NormalizedEntityType =
  | 'place'
  | 'restaurant'
  | 'hotel'
  | 'destination'
  | 'product'
  | 'experience'
  | 'media'
  | 'event'
  | 'generic';

/** What kind of thing this object actually is, semantically. */
export type EntityRole =
  /** A selectable, comparable peer — the only role allowed in candidate sets. */
  | 'entity'
  /** A property OF something (price range, group size, available slots). */
  | 'attribute'
  /** Context that helps the user but isn't a choice (booking tips, caveats). */
  | 'supporting';

export interface NormalizedEntity {
  id: string;
  type: NormalizedEntityType;

  title?: string;
  subtitle?: string;

  /** Optional by design. Never assume this exists. */
  image?: string;

  rating?: number;
  reviewCount?: number;

  price?: string;

  location?: string;

  distance?: string;
  travelTime?: string;

  availability?: unknown;

  /** Relative strength within its own candidate set, when the source data
   *  genuinely supports one. Absent is the honest default — a set with no
   *  scores must not be presented as ranked. */
  score?: number;

  /** Stable cross-tool identifier (e.g. Google Places place_id) used to
   *  correlate the same real-world thing across search -> details -> final
   *  response without relying on title-string matching. */
  externalId?: string;

  /** The agent's own short concluding read (a `<badge>` value). An opinion,
   *  not a fact. */
  judgment?: string;
  /** A fuller sentence the agent itself wrote about this entity (a `<why>`
   *  block). Never generated by the adapter. */
  reasoning?: string;
  /** Short factual bullets the comparison rests on. */
  evidence?: string[];

  attributes?: Record<string, unknown>;
  raw?: unknown;
}

/** An object the agent emitted that is NOT a comparable peer. Kept rather
 *  than discarded — it is real content worth showing in the final response's
 *  supporting section, just never as a ranked candidate. */
export interface NonEntityBlock {
  role: Exclude<EntityRole, 'entity'>;
  title?: string;
  lines: string[];
  raw?: unknown;
}

/** Result of splitting a raw extracted set into comparable peers and
 *  everything else. */
export interface EntityPartition {
  entities: NormalizedEntity[];
  supporting: NonEntityBlock[];
}
