/* ─────────────────────────────────────────────────────────────────────────────
   LEVEL 2B — Semantic event / entity model.

   The intermediate representation between raw Phoenix spans and Level 2's
   AgentMutation vocabulary (see src/types/progressiveValue.ts). Keeps
   Phoenix-specific parsing (span names, attribute keys, tool.input/output
   shapes) out of the mutation-mapping logic — a future live-events source or
   a different domain's tool set only needs to produce these two shapes, not
   understand Phoenix at all.

     PhoenixSpan[] -> SemanticAgentEvent[] -> AgentMutation[] -> ExperiencePassDef[]

   Not domain-specific: `ExtractedEntity` covers place/hotel/restaurant today
   because that's what real aitv-mewtwo-harness traces have produced so far
   (see LEVEL2_INSTRUMENTATION_GAPS.md), but the shape carries no travel-only
   fields at the top level for that reason.
   ───────────────────────────────────────────────────────────────────────────── */

export type SemanticEventType =
  | 'search'
  | 'retrieve'
  | 'maps'
  | 'availability'
  | 'enrichment'
  | 'compare'
  | 'rank'
  | 'filter'
  | 'synthesis'
  | 'schedule'
  | 'clarify'
  | 'final'
  /** A recognised operation with no consumer meaning of its own (routing,
   *  guardrails, schema transforms, memory reads). Kept as an event so
   *  developer diagnostics can account for it, then filtered out by the
   *  user-value classifier before any pass is built — see
   *  src/level2/userValue/visibility.ts. */
  | 'internal'
  | 'unknown';

export type MappingConfidence = 'high' | 'medium' | 'low';

export type ExtractedEntityType =
  | 'place'
  | 'hotel'
  | 'restaurant'
  | 'product'
  | 'recipe'
  | 'media'
  | 'event'
  | 'generic';

export interface ExtractedEntity {
  id: string;
  type: ExtractedEntityType;

  title?: string;
  subtitle?: string;
  image?: string;

  rating?: number;
  reviewCount?: number;

  price?: string;
  distance?: string;
  travelTime?: string;
  /** Real opening-hours/time-slot text (e.g. a `<hours>` tag, or
   *  PlaceDetails' `opening_hours` array joined) — never inferred. */
  availability?: string;

  /** A real synthesized line the agent itself wrote about this entity (e.g.
   *  a `<why>` block in the final response) — never generated by the
   *  adapter. Distinct from `judgment`, which is a short concluding read
   *  (e.g. a `<badge>`); this is the fuller sentence. */
  reasoning?: string;
  /** Short concluding read, e.g. a `<badge>` value ("Top Pick"). */
  judgment?: string;

  score?: number;

  /** Provider-specific identifier (e.g. Google Places `place_id`) used to
   *  correlate the same real-world entity across multiple tool calls
   *  (search -> details -> final response) without relying on title-string
   *  matching, which is far less reliable. */
  externalId?: string;

  attributes?: Record<string, unknown>;
  raw?: unknown;
}

export interface SemanticAgentEvent {
  id: string;
  type: SemanticEventType;

  sourceSpanIds: string[];

  /** ms, relative to the trace's own start (traceStart subtracted already) —
   *  never a Phoenix-absolute timestamp past this point in the pipeline. */
  startTime: number;
  endTime: number;

  /** Plain-language line describing what the agent was doing, derived from
   *  real tool semantics (see adapters/semanticEvents.ts's TOOL_SIGNALS) —
   *  never a raw span/tool name. */
  narration: string;

  input?: unknown;
  output?: unknown;

  entities?: ExtractedEntity[];

  metadata?: Record<string, unknown>;
}
